### ISSUE TITLE
Could I ask a question about the extra_model_paths.yaml file in ComfyUI Package?

### ISSUE THREAD

**Issue by ZeroizeHD** [LykosAI/StabilityMatrix#882]
### Package

I want to add the path to a checkpoint in the extra_model_paths.yaml file in ComfyUI, 
but when I modify the file, it doesn't work as expected. 
Moreover, the modified data gets reverted to its original state. 
If I set the file to read-only, it fails to run due to lack of write permissions.

### When did the issue occur?

Running the Package

### What GPU / hardware type are you using?

Nvidia RTX 6000 ADA with CUDA

### File A
```yaml
stability_matrix:
  checkpoints: E:\StabilityMatrix\Data\Models\StableDiffusion
  vae: E:\StabilityMatrix\Data\Models\VAE
  loras: >-
    E:\StabilityMatrix\Data\Models\Lora

    E:\StabilityMatrix\Data\Models\LyCORIS
  upscale_models: >-
    E:\StabilityMatrix\Data\Models\ESRGAN

    E:\StabilityMatrix\Data\Models\RealESRGAN

    E:\StabilityMatrix\Data\Models\SwinIR
  embeddings: E:\StabilityMatrix\Data\Models\TextualInversion
  hypernetworks: E:\StabilityMatrix\Data\Models\Hypernetwork
  controlnet: >-
    E:\StabilityMatrix\Data\Models\ControlNet

    E:\StabilityMatrix\Data\Models\T2IAdapter
  clip: E:\StabilityMatrix\Data\Models\CLIP
  clip_vision: E:\StabilityMatrix\Data\Models\InvokeClipVision
  diffusers: E:\StabilityMatrix\Data\Models\Diffusers
  gligen: E:\StabilityMatrix\Data\Models\GLIGEN
  vae_approx: E:\StabilityMatrix\Data\Models\ApproxVAE
  ipadapter: >-
    E:\StabilityMatrix\Data\Models\IpAdapter

    E:\StabilityMatrix\Data\Models\InvokeIpAdapters15

    E:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
  prompt_expansion: E:\StabilityMatrix\Data\Models\PromptExpansion
  unet: E:\StabilityMatrix\Data\Models\unet

```

### File B
```yaml
stability_matrix:
  checkpoints: >-
    E:\StabilityMatrix\Data\Models\StableDiffusion
    E:\StabilityMatrix\resource\models\checkpoints

  vae: >-
    E:\StabilityMatrix\Data\Models\VAE
    E:\StabilityMatrix\resource\models\vae

  loras: >-
    E:\StabilityMatrix\Data\Models\Lora
    E:\StabilityMatrix\Data\Models\LyCORIS
    E:\StabilityMatrix\resource\models\loras

  upscale_models: >-
    E:\StabilityMatrix\Data\Models\ESRGAN
    E:\StabilityMatrix\Data\Models\RealESRGAN
    E:\StabilityMatrix\Data\Models\SwinIR
    E:\StabilityMatrix\resource\models\upscale_models

  embeddings: >-
    E:\StabilityMatrix\Data\Models\TextualInversion
    E:\StabilityMatrix\resource\models\embeddings

  hypernetworks: >-
    E:\StabilityMatrix\Data\Models\Hypernetwork
    E:\StabilityMatrix\resource\models\hypernetworks

  controlnet: >-
    E:\StabilityMatrix\Data\Models\ControlNet
    E:\StabilityMatrix\Data\Models\T2IAdapter
    E:\StabilityMatrix\resource\models\controlnet

  clip: >-
    E:\StabilityMatrix\Data\Models\CLIP
    E:\StabilityMatrix\resource\models\clip

  clip_vision: >-
    E:\StabilityMatrix\Data\Models\InvokeClipVision
    E:\StabilityMatrix\resource\models\clip_vision

  diffusers: >-
    E:\StabilityMatrix\Data\Models\Diffusers
    E:\StabilityMatrix\resource\models\diffusers

  gligen: >-
    E:\StabilityMatrix\Data\Models\GLIGEN
    E:\StabilityMatrix\resource\models\gligen

  vae_approx: >-
    E:\StabilityMatrix\Data\Models\ApproxVAE
    E:\StabilityMatrix\resource\models\vae_approx

  ipadapter: >-
    E:\StabilityMatrix\Data\Models\IpAdapter
    E:\StabilityMatrix\Data\Models\InvokeIpAdapters15
    E:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
    E:\StabilityMatrix\resource\models\ipadapter

  unet: >-
    E:\StabilityMatrix\Data\Models\unet
    E:\StabilityMatrix\resource\models\unet

  prompt_expansion: >-
    E:\StabilityMatrix\Data\Models\PromptExpansion

  configs: >-
    E:\StabilityMatrix\resource\models\configs

  facerestore_models: >-
    E:\StabilityMatrix\resource\models\facerestore_models

  grounding-dino: >-
    E:\StabilityMatrix\resource\models\grounding-dino

  insightface: >-
    E:\StabilityMatrix\resource\models\insightface

  mimicmotion: >-
    E:\StabilityMatrix\resource\models\mimicmotion

  mmdets: >-
    E:\StabilityMatrix\resource\models\mmdets

  onnx: >-
    E:\StabilityMatrix\resource\models\onnx

  photomaker: >-
    E:\StabilityMatrix\resource\models\photomaker

  sams: >-
    E:\StabilityMatrix\resource\models\sams

  style_models: >-
    E:\StabilityMatrix\resource\models\style_models

  ultralytics: >-
    E:\StabilityMatrix\resource\models\ultralytics

``` 

### File C
```yaml
stability_matrix:
  checkpoints: E:\StabilityMatrix\Data\Models\StableDiffusion
  vae: E:\StabilityMatrix\Data\Models\VAE
  loras: >-
    E:\StabilityMatrix\Data\Models\Lora

    E:\StabilityMatrix\Data\Models\LyCORIS
  upscale_models: >-
    E:\StabilityMatrix\Data\Models\ESRGAN

    E:\StabilityMatrix\Data\Models\RealESRGAN

    E:\StabilityMatrix\Data\Models\SwinIR
  embeddings: E:\StabilityMatrix\Data\Models\TextualInversion
  hypernetworks: E:\StabilityMatrix\Data\Models\Hypernetwork
  controlnet: >-
    E:\StabilityMatrix\Data\Models\ControlNet

    E:\StabilityMatrix\Data\Models\T2IAdapter
  clip: E:\StabilityMatrix\Data\Models\CLIP
  clip_vision: E:\StabilityMatrix\Data\Models\InvokeClipVision
  diffusers: E:\StabilityMatrix\Data\Models\Diffusers
  gligen: E:\StabilityMatrix\Data\Models\GLIGEN
  vae_approx: E:\StabilityMatrix\Data\Models\ApproxVAE
  ipadapter: >-
    E:\StabilityMatrix\Data\Models\IpAdapter

    E:\StabilityMatrix\Data\Models\InvokeIpAdapters15

    E:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
  unet: E:\StabilityMatrix\Data\Models\unet
  prompt_expansion: E:\StabilityMatrix\Data\Models\PromptExpansion
  configs: >-
    E:\StabilityMatrix\resource\models\configs
  facerestore_models: >-
    E:\StabilityMatrix\resource\models\facerestore_models
  grounding-dino: >-
    E:\StabilityMatrix\resource\models\grounding-dino
  insightface: >-
    E:\StabilityMatrix\resource\models\insightface
  mimicmotion: >-
    E:\StabilityMatrix\resource\models\mimicmotion
  mmdets: >-
    E:\StabilityMatrix\resource\models\mmdets
  onnx: >-
    E:\StabilityMatrix\resource\models\onnx
  photomaker: >-
    E:\StabilityMatrix\resource\models\photomaker
  sams: >-
    E:\StabilityMatrix\resource\models\sams
  style_models: >-
    E:\StabilityMatrix\resource\models\style_models
  ultralytics: >-
    E:\StabilityMatrix\resource\models\ultralytics

``` 

I initially changed File A to File B and added paths for the checkpoint and some other items. 
I saved it as File B, but when I launch through StabilityMatrix, it gets changed to File C. 
Is there a way to set multiple paths for checkpoints or VAE?

### Console output

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-12 17:26:57.563931
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image\venv\Scripts\python.exe
** ComfyUI Path: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image
** Log path: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image\comfyui.log

Prestartup times for custom nodes:
   0.7 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image\custom_nodes\ComfyUI-Manager

Total VRAM 46068 MB, total RAM 261516 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX 6000 Ada Generation : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image\web
Adding extra search path checkpoints E:\StabilityMatrix\Data\Models\StableDiffusion
Adding extra search path vae E:\StabilityMatrix\Data\Models\VAE
Adding extra search path loras E:\StabilityMatrix\Data\Models\Lora
Adding extra search path loras E:\StabilityMatrix\Data\Models\LyCORIS
Adding extra search path upscale_models E:\StabilityMatrix\Data\Models\ESRGAN
Adding extra search path upscale_models E:\StabilityMatrix\Data\Models\RealESRGAN
Adding extra search path upscale_models E:\StabilityMatrix\Data\Models\SwinIR
Adding extra search path embeddings E:\StabilityMatrix\Data\Models\TextualInversion
Adding extra search path hypernetworks E:\StabilityMatrix\Data\Models\Hypernetwork
Adding extra search path controlnet E:\StabilityMatrix\Data\Models\ControlNet
Adding extra search path controlnet E:\StabilityMatrix\Data\Models\T2IAdapter
Adding extra search path clip E:\StabilityMatrix\Data\Models\CLIP
Adding extra search path clip_vision E:\StabilityMatrix\Data\Models\InvokeClipVision
Adding extra search path diffusers E:\StabilityMatrix\Data\Models\Diffusers
Adding extra search path gligen E:\StabilityMatrix\Data\Models\GLIGEN
Adding extra search path vae_approx E:\StabilityMatrix\Data\Models\ApproxVAE
Adding extra search path ipadapter E:\StabilityMatrix\Data\Models\IpAdapter
Adding extra search path ipadapter E:\StabilityMatrix\Data\Models\InvokeIpAdapters15
Adding extra search path ipadapter E:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
Adding extra search path unet E:\StabilityMatrix\Data\Models\unet
Adding extra search path prompt_expansion E:\StabilityMatrix\Data\Models\PromptExpansion
Adding extra search path configs E:\StabilityMatrix\resource\models\configs
Adding extra search path facerestore_models E:\StabilityMatrix\resource\models\facerestore_models
Adding extra search path grounding-dino E:\StabilityMatrix\resource\models\grounding-dino
Adding extra search path insightface E:\StabilityMatrix\resource\models\insightface
Adding extra search path mimicmotion E:\StabilityMatrix\resource\models\mimicmotion
Adding extra search path mmdets E:\StabilityMatrix\resource\models\mmdets
Adding extra search path onnx E:\StabilityMatrix\resource\models\onnx
Adding extra search path photomaker E:\StabilityMatrix\resource\models\photomaker
Adding extra search path sams E:\StabilityMatrix\resource\models\sams
Adding extra search path style_models E:\StabilityMatrix\resource\models\style_models
Adding extra search path ultralytics E:\StabilityMatrix\resource\models\ultralytics
### ComfyUI Revision: 2679 [d247bc5a] | Released on '2024-09-12'

Import times for custom nodes:
   0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image\custom_nodes\websocket_image_save.py
   0.2 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI_Flux_Make_Image\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

Stopped process at 9/12/2024 5:29:08 PM +09:00

### Version

v2.11.0

### What Operating System are you using?

Windows
